### PR TITLE
Correct AllowedParents

### PR DESCRIPTION
**Pull request by skybber**

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Thank you. :)

**Comment by skybber** [comment]
Hi, thanks for the project! I've noticed it when I've rewriting components to java. My original intention was to use mjml referential implementation as a starting point but mjml-net is much better since similarity of languages.

**Comment by skybber** [comment]
Yes, the performance of the JS implementation is pain, it was the reason why I've started with rewriting it. Btw instead of XML parser I'm using flex (jflex) lexical analyser + simple parser since html could not be strict XML.

**Comment by SebastianStehle** [comment]
But mjml IS strict XML afaik.

**Comment by SebastianStehle** [comment]
Do you have a link to your code?

**Comment by skybber** [comment]
It is still not finished.

**Comment by SebastianStehle** [comment]
Who cares ... ;)

**Comment by skybber** [comment]
Far from complete state : https://github.com/skybber/mjmland 

What about to create GH organization dedicated to alternative mjml parsers ?

**Comment by SebastianStehle** [comment]
> What about to create GH organization dedicated to alternative mjml parsers ?

Why not? Or something like mjml-contrib?

**Comment by SebastianStehle** [comment]
It looks very similar to our implementation :)

**Comment by skybber** [comment]
It is hand crafted, .net implementation helps a lot.

**Comment by SebastianStehle** [comment]
You could also ask the rust guy if he would like to join the orga.

**Comment by skybber** [comment]
> > What about to create GH organization dedicated to alternative mjml parsers ?
> 
> Why not? Or something like mjml-contrib?
May be, but I would give it some more time. I expect to have a working parser/generator next week, so there's time.

**Comment by skybber** [comment]
> Why not? Or something like mjml-contrib?

mjml-contrib / mjml-engines / mjml-tools (umbrella for not only parsers) / mjml-impl / mjml-plus

Maybe we can think of a better name.

**Comment by skybber** [comment]
Btw it could be nice if the projects share some kind of mjml-compatibility set of tests. This might be doable if every parser had a command line mode.

**Comment by SebastianStehle** [comment]
> Btw it could be nice if the projects share some kind of mjml-compatibility set of tests. This might be doable if every parser had a command line mode.

I have asked mjml team for that, but they have almost no tests. If all tools would provide a CLI then we could also write a CLI took to compare html files and then write an script for that.

Comparing HTML was one of the biggest challenges in the .NET implementation.

**Comment by SebastianStehle** [comment]
Btw: this is the code that is generated: https://gist.github.com/SebastianStehle/cbe7f280a506f1d11a2a7deda1812321

I guess you can also solve it with reflection, but I wanted to try source generators (a new concept in C#).

**Comment by skybber** [comment]
I'm using reflection, it is 5x slower then direct call, some 5*10^-9s. It takes ~1% of total parser time.

**Comment by SebastianStehle** [comment]
Yes, makes sense

**Comment by skybber** [comment]
So the more complex component is Attributes, which processes attr values into GlobalContext. I haven't solved this yet,

**Pull request merged**
